DROP DATABASE IF EXISTS gamesDB;

CREATE DATABASE gamesDB;

USE gamesDB;

CREATE TABLE games (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  rating INT NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);